---
- name: Update and upgrade Ubuntu 22.04
  hosts: all
  become: yes  # to run with sudo privileges
  tasks:

    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Update the cache if it's older than 1 hour

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist  # Perform a dist-upgrade (includes kernel and dependencies)

    - name: Auto-remove unnecessary packages
      apt:
        autoremove: yes

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if needed
      reboot:
        msg: "Rebooting the server because updates were installed that require it"
        test_command: whoami
      when: reboot_required.stat.exists
